### PR TITLE
feat(kaktwoos): adjusted kaktwoos to use floor_level as commandline parameter

### PR DESCRIPTION
**Pull request by BoySanic**
There's a few other changes here, including:

1. Changed kaktwoos Assimilator to match kaktoos assimilator, floor level grouped files
2. Changed Min quorum from 1 to 2
3. Fixed standalone mode in the binary
4. Fixed workflow in the binary repo as it became severely outdated and github deprecated several features we had in use
5. Changed kaktwoos cl file and all main files so that the floor_level macro is defined

### CODE REVIEW

**Comment by BoySanic** [comment]
Hashes:

Windows:
Nvidia: B358AE755D42623657C2F6FCF745D69B8B8EE7742B8C19C33E3732CDC45D23BB
AMD: 0E19F02F727718DB3B99ACA427281A5C1E385AB96DA9CC11266ED5EFDDA4197E
Intel: 3EA62E5C2957EB72911348EBB061B897BDEFCB21B187FC503D032FA4235F8746

Linux:
Nvidia: D35929C42A858BEC429AAD14619F1355E717345BE0001D1B280FE966EDBBE209
AMD: FAAF1791A4D84DD03C4F8FC75B50F36F22F2FF4636C835A579B1EF947CED7213
Intel: 31B0D305048B7297789D4B12923052D18FB04D508988FD6F6E8D7665FF1CBB79

**Comment by Hyenadae** [comment]
Finally, we can do kaktwoos v2.1.0!

**Review by Hyenadae — APPROVED** [review]
Looks alright to me. We tested this in boysanic's own boinc environment, connected to it and did debugs. Just remember to ensure the validator and other scripts are given permission.

**Review by hube12 — COMMENTED** [review]
Looks good

**Review by hube12 — DISMISSED** [review]

**Comment by DutChen18** [comment]
why no 62 and 63?
might as well redo those while we're at it

**Comment by BoySanic** [comment]
> why no 62 and 63?
> might as well redo those while we're at it

I've added those data files now so that we can simply change the makeproject script on the server side to start those heights. It's 2 characters and we don't need to write another commit for every little change to execute those workunits.

Should be good!

**Review by Hyenadae — DISMISSED** [review]

**Review by DutChen18 — APPROVED** [review]
Pig

**Review by hube12 — APPROVED** [review]

**Review by Hyenadae — APPROVED** [review]
Sure, add more seeds!

**Review by Hyenadae — APPROVED** [review]

**Review by MrSpike63 — APPROVED** [review]
Looks good to me

**Pull request merged**
