### PR TITLE
feat: Add TrailerTCrack project

### PR DESCRIPTION
**Pull request by MrSpike63**
Add support for the https://github.com/MrSpike63/TrailerTCrack project, aiming to crack the Trailer Thumbnail 2 Seed.

### CODE REVIEW

**Review by BoySanic — APPROVED** [review]
Looks good to me! Tested on baldhome enough to know it'll at least provide results correctly.

**Comment by Hyenadae** [comment]
Worked fine on the test mchome yeah, sent in a few tasks. I'm not clear how we know it provides the right result for the tree (does it just output all seeds that are likely the trailer scene's world/blocks?) but the code itself looks fine. What about if it works or any errors on Linux Nvidia?

**Review by Hyenadae — APPROVED** [review]
Looks good. Will be fun to see if this assimilator/validator cries on Linux vs Windows line endings for the seed (unlikely though)

**Review by hube12 — APPROVED** [review]
Ok python wise I don't see any issues, for the apps, I tried them, they do run on windows and linux (fedora x64)

**Pull request merged**
