### PR TITLE
feat(new website): Add new website url rewrite

### PR DESCRIPTION
**Pull request by hube12**
https://minecraftathome.com/minecrafthome/beta/
https://minecraftathome.com/beta/

### CODE REVIEW

**Comment by ChipWolf** [comment]
@hube12 it's probably better to add the paths to traefik and add an nginx container for all the new static shit

**Comment by hube12** [comment]
> @hube12 it's probably better to add the paths to traefik and add an nginx container for all the new static shit

I agree, the apache redirect/rewrite was temporary, I will make the change so the docker router can actually do it and serve the static as a separate container (maybe behind a nginx proxy). It would have been way easier to do so in kubernetes ;)

**Comment by ChipWolf** [comment]
Yeah, we'll get K8s on the go soon

**Review by DutChen18 — APPROVED** [review]
h

**Review by BoySanic — APPROVED** [review]
Looks good to me!

**Review by BalintCsala — APPROVED** [review]

**Pull request merged**
