### PR TITLE
feat(kaktwoos): v2.13, config changes, improved optimization toggler for amd and nvidia, checkpoint fixes

### PR DESCRIPTION
**Pull request by Hyenadae**
See: https://github.com/minecrafthome/kaktwoos-cl/pull/24
Rebased off of latest code (May 02, 2021)

Finally changed the optimizations / GPU checker to be the same on AMD and Nvidia.
Includes version.xml additions for amd/nvidia gpu opencl files
Meaning, AMD and Nvidia both need their respective kaktwoos-cl files and kaktwoos.cl (generic) now

Changes:
AMD now uses kaktwoos-amd.cl by default, and kaktwoos.cl for fallback on any RDNA1/2 GPU
Nvidia now uses kaktwoos.cl by default, and kaktwoos-nv.cl for increased speed on GTX 1600 + RTX gpus

No changes for Intel.
All files run through DOS2UNIX for future sanity.
Checkpoints now read and write the current task's 'end' position, though unsure if further checkpoint verification should be coded in considering the end is near for kaktwoos-cl

### CODE REVIEW

**Comment by Hyenadae** [comment]
I've got one more commit that (due to git accidents) isn't showing here. 

https://github.com/Hyenadae/kaktwoos-cl/commit/b116fa9cf3a89ae9aa328d51d3e68adb5a5e3450 
https://github.com/minecrafthome/kaktwoos-cl/pull/25 

It should be fine (once the above has a second round of testing) to use the latest kaktwoos-cl binaries which will include those fixes, and then make the "final" 2.13 version

**Review by BoySanic — APPROVED** [review]
LGTM :shipit: 

I don't see anything fundamentally wrong with it as long as it works.

**Review by hube12 — APPROVED** [review]
LGTM,
My only concern was the new geforce name handling for weird gpu but those will not be detected by boinc anyway (and if we have any we will log them and bump them down to an old version)

**Comment by Hyenadae** [comment]
Choo choo, all aboard the review train!

**Review by MrSpike63 — APPROVED** [review]
LGTM

**Pull request merged**
