### PR TITLE
fix: multiple errors in the websites

### PR DESCRIPTION
**Pull request by hube12**

### CODE REVIEW

**Comment by ChipWolf** [comment]
Why produce hourly stats btw? Is this required for something?

**Comment by hube12** [comment]
> Why produce hourly stats btw? Is this required for something?

Philipp wanted that, it's not required per say but it allows to report more frequently to boincstat.

**Review by BoySanic — APPROVED** [review]
I don't see any issues here, and it seems we're running this already :)

**Review by Hyenadae — APPROVED** [review]
Doesn't look like too many changes :)

**Review by MrSpike63 — APPROVED** [review]
If we are already running this, looks good to me

**Pull request merged**
