### PR TITLE
fix(boinc): fixed mistake with validator regex affecting linux line endings

### PR DESCRIPTION
**Pull request by BoySanic**
Problem discovered during early stages of the new round of work.

Big thanks to Neil for helping us look through everything so late at night and providing a patch for the regex 
😊

### CODE REVIEW

**Review by MrSpike63 — CHANGES_REQUESTED** [review]
The regex you added "(:?\n|\r\n)" is different from "(?:\n|\r\n)".

**Review by MrSpike63 — DISMISSED** [review]
Looks good

**Comment by Hyenadae** [comment]
OH BOY OH JEEZ AAAH FIX

**Review by Hyenadae — DISMISSED** [review]
BOINC ME UP INSIDE

**Review by hube12 — COMMENTED** [review]
([\s\S]*?)(?:\n|\r\n)

**Comment by Hyenadae** [comment]
Oh boy we can merge this and do other cool things now!

**Review by hube12 — APPROVED** [review]
perfect

**Comment by Hyenadae** [comment]
#68

**Pull request closed without merging**
